#!/bin/python

import requests

# This is the original page for the change log:
#     https://discord.com/developers/docs/change-log
# The page appears to get generated by this file:
#     https://raw.githubusercontent.com/discord/discord-api-docs/main/docs/Change_Log.md
# This script uses the Change_Log.md file from GitHub to parse the changelog into a csv format


def get_changelog():
    discord_changelog_md_url = "https://raw.githubusercontent.com/discord/discord-api-docs/main/docs/Change_Log.md"
    request = requests.get(discord_changelog_md_url)
    changelog = request.content.decode("utf-8").split("\n")

    return changelog


def main():
    changelog = get_changelog()

    #for line in changelog:
    #    print(line)

    for line in changelog:
        
        if not line:
            line = line
        if line == "# Change Log":
            line = line
        elif line.startswith("#### "):
            print("DATE " + line)
        elif line.startswith("## "):
            print("HEADER " + line)
        elif line.startswith("- "):
            print("LISTFIRSTLEVEL " + line)
        elif line.startswith("  - "):
            print("LISTSECONDLEVEL " + line)
        else:
            print(line)

if __name__:
    main()